#!/bin/bash

master_file=./template.svg
output_folder=./output
stains_matcher="__STAINS__"
meshes_matcher="__MESHES__"
colors_file=./colors.csv

create_file_name()
{
  color_name=$1
  rgb=$2

  distinction="${rgb}"

  if [[ ${color_name} != "" ]]; then
    distinction="${color_name}"
  fi

  echo "${output_folder}/1up_${distinction}.svg"
}

create_1up()
{
  stains_color=$1
  meshes_color=$2
  color_name=$3
  target_file_name=`create_file_name ${color_name} ${stains_color}`
  cmd="cat ${master_file} | sed -E \"s/${stains_matcher}/${stains_color}/\" | sed -E \"s/${meshes_matcher}/${meshes_color}/\" > ${target_file_name}"
  echo ${cmd}
  bash -c "${cmd}"
}

while IFS=, read -r stains_color meshes_color color_name; do
  create_1up ${stains_color} ${meshes_color} ${color_name}
done < ./colors.csv
